name: Deploy to CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Pull latest changes and build on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@13.203.58.181 "
            cd ~/full-stack-app-with-react-rest-api &&
            git config --global credential.helper 'cache --timeout=3600' &&
            git config --global user.email 'github-actions@github.com' &&
            git config --global user.name 'GitHub Actions' &&
            git checkout main &&
            git pull https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/niharkushwah/full-stack-app-with-react-rest-api.git main &&
            cd client &&
            ls &&
            npm install &&
            npm run build &&
            aws s3 sync ./build s3://pradhumna-cdn/cdn &&
            aws cloudfront create-invalidation --distribution-id E2DT4H7SW7LG39 --paths "/*"
          "
