name: Deploy to CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Pull latest changes and build on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@13.203.58.181 "
            cd ~/full-stack-app-with-react-rest-api &&
            git config --global credential.helper 'cache --timeout=3600' &&
            git config --global user.email 'github-actions@github.com' &&
            git config --global user.name 'GitHub Actions' &&
            git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/your-username/your-repo.git main &&
            cd client &&
            npm install &&
            npm run build
          "

      - name: Debug EC2 Build Directory
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@13.203.58.181 "ls -la /"

      - name: Copy build folder from EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ubuntu@13.203.58.181:~/full-stack-app-with-react-rest-api/client/build ./build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files to S3
        run: aws s3 sync ./build s3://pradhumna-cdn/cdn --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2DT4H7SW7LG39 --paths "/*"
